// Define action constants
module.exports = {
  ADD_MOVIE: "ADD_MOVIE",
  GET_ALL_MOVIES: "GET_ALL_MOVIES",
  CREATE_MOVIE: "CREATE_MOVIE",
  UPDATE_MOVIE: "UPDATE_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE"
};
