// Define action constants
module.exports = {
  GET_DINOSAURS: "GET_DINOSAURS",
  GET_DINOSAUR: "GET_DINOSAUR",
  CREATE_DINOSAUR: "CREATE_DINOSAUR",
  UPDATE_DINOSAUR: "UPDATE_DINOSAUR",
  DELETE_DINOSAUR: "DELETE_DINOSAUR"
};
